"""Initial migration

Revision ID: 385f0e8dc673
Revises: 
Create Date: 2025-12-23 02:47:15.170820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '385f0e8dc673'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('board_key', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('code_version', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('success', 'failed', 'partial')", name='check_pipeline_runs_status'),
    sa.PrimaryKeyConstraint('run_id'),
    sa.UniqueConstraint('target_date', 'board_key', name='uq_pipeline_runs_date_board')
    )
    op.create_table('terms',
    sa.Column('term_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('normalized', sa.Text(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('surface_examples', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('term_id'),
    sa.UniqueConstraint('normalized')
    )
    op.create_table('daily_term_stats',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('board_key', sa.Text(), nullable=False),
    sa.Column('term_id', sa.BigInteger(), nullable=False),
    sa.Column('post_hits', sa.Integer(), nullable=False),
    sa.Column('thread_hits', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('post_hits >= 0', name='check_daily_term_stats_post_hits'),
    sa.CheckConstraint('thread_hits >= 0', name='check_daily_term_stats_thread_hits'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.term_id'], ),
    sa.PrimaryKeyConstraint('date', 'board_key', 'term_id')
    )
    op.create_table('pipeline_metrics_daily',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('board_key', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('fetched_threads', sa.Integer(), nullable=False),
    sa.Column('fetched_posts', sa.Integer(), nullable=False),
    sa.Column('parsed_posts', sa.Integer(), nullable=False),
    sa.Column('parse_fail_posts', sa.Integer(), nullable=False),
    sa.Column('tokenize_fail_posts', sa.Integer(), nullable=False),
    sa.Column('filtered_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('filtered_rate', sa.Double(), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_sec >= 0', name='check_pipeline_metrics_daily_duration_sec'),
    sa.CheckConstraint('fetched_posts >= 0', name='check_pipeline_metrics_daily_fetched_posts'),
    sa.CheckConstraint('fetched_threads >= 0', name='check_pipeline_metrics_daily_fetched_threads'),
    sa.CheckConstraint('filtered_rate >= 0 AND filtered_rate <= 1', name='check_pipeline_metrics_daily_filtered_rate'),
    sa.CheckConstraint('filtered_tokens >= 0', name='check_pipeline_metrics_daily_filtered_tokens'),
    sa.CheckConstraint('parse_fail_posts >= 0', name='check_pipeline_metrics_daily_parse_fail_posts'),
    sa.CheckConstraint('parsed_posts >= 0', name='check_pipeline_metrics_daily_parsed_posts'),
    sa.CheckConstraint('tokenize_fail_posts >= 0', name='check_pipeline_metrics_daily_tokenize_fail_posts'),
    sa.CheckConstraint('total_tokens >= 0', name='check_pipeline_metrics_daily_total_tokens'),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.run_id'], ),
    sa.PrimaryKeyConstraint('date', 'board_key')
    )
    op.create_table('term_regression_results',
    sa.Column('board_key', sa.Text(), nullable=False),
    sa.Column('term_id', sa.BigInteger(), nullable=False),
    sa.Column('intercept', sa.Double(), nullable=False),
    sa.Column('slope', sa.Double(), nullable=False),
    sa.Column('intercept_ci_lower', sa.Double(), nullable=True),
    sa.Column('intercept_ci_upper', sa.Double(), nullable=True),
    sa.Column('slope_ci_lower', sa.Double(), nullable=True),
    sa.Column('slope_ci_upper', sa.Double(), nullable=True),
    sa.Column('p_value', sa.Double(), nullable=True),
    sa.Column('analysis_start_date', sa.Date(), nullable=False),
    sa.Column('analysis_end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('p_value >= 0 AND p_value <= 1', name='check_term_regression_results_p_value'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.term_id'], ),
    sa.PrimaryKeyConstraint('board_key', 'term_id')
    )
    op.create_table('weekly_term_trends',
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('board_key', sa.Text(), nullable=False),
    sa.Column('term_id', sa.BigInteger(), nullable=False),
    sa.Column('post_hits', sa.Integer(), nullable=False),
    sa.Column('total_posts', sa.Integer(), nullable=False),
    sa.Column('appearance_rate', sa.Double(), nullable=False),
    sa.Column('appearance_rate_ci_lower', sa.Double(), nullable=True),
    sa.Column('appearance_rate_ci_upper', sa.Double(), nullable=True),
    sa.Column('zscore', sa.Double(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('appearance_rate >= 0 AND appearance_rate <= 1', name='check_weekly_term_trends_appearance_rate'),
    sa.CheckConstraint('appearance_rate_ci_lower >= 0 AND appearance_rate_ci_lower <= 1', name='check_weekly_term_trends_ci_lower'),
    sa.CheckConstraint('appearance_rate_ci_upper >= 0 AND appearance_rate_ci_upper <= 1', name='check_weekly_term_trends_ci_upper'),
    sa.CheckConstraint('post_hits >= 0', name='check_weekly_term_trends_post_hits'),
    sa.CheckConstraint('total_posts >= 0', name='check_weekly_term_trends_total_posts'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.term_id'], ),
    sa.PrimaryKeyConstraint('week_start_date', 'board_key', 'term_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_term_trends')
    op.drop_table('term_regression_results')
    op.drop_table('pipeline_metrics_daily')
    op.drop_table('daily_term_stats')
    op.drop_table('terms')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
